# SITE SETTINGS
title: Chronometric Age Extension
description: Vocabulary maintained by the Darwin Core Maintenance Interest Group to facilitate the sharing of information about chronometric ages and the techniques used to determine them.
# url: "https://chrono.tdwg.org/"
navbar:
  left:
  - text: Terms
    href: terms/
  right:
  - text: GitHub
    href: https://github.com/tdwg/chrono

# BUILD SETTINGS
markdown: kramdown
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
